FROM ubuntu:20.04

# Enviroment
ENV DEBIAN_FRONTEND noninteractive

# Install dependency
RUN set -eux \
    && apt-get update -y \
    && apt-get install -y debhelper libz-dev default-jdk \
                          ant tcl rsync zip python3 systemd \
    && apt-get clean all
