FROM rockylinux:9.3

# Install dependency other
RUN set -eux \
    && yum install -y python3 automake make gcc gcc-c++ \
                      java ant zlib-devel tcl zip rpm-build rsync procps-ng systemd \
    && yum clean all
