/*
	Copyright (c) 2017 TOSHIBA Digital Solutions Corporation

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as
	published by the Free Software Foundation, either version 3 of the
	License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Affero General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef PARSERTOKEN_H
#define PARSERTOKEN_H
#define TK_SEMI                             1
#define TK_EXPLAIN                          2
#define TK_ANALYZE                          3
#define TK_BEGIN                            4
#define TK_TRANSACTION                      5
#define TK_COMMIT                           6
#define TK_END                              7
#define TK_ROLLBACK                         8
#define TK_TABLE                            9
#define TK_LP                              10
#define TK_RP                              11
#define TK_CREATE                          12
#define TK_IF                              13
#define TK_NOT                             14
#define TK_EXISTS                          15
#define TK_COMMA                           16
#define TK_PRIMARY                         17
#define TK_KEY                             18
#define TK_NULL                            19
#define TK_AS                              20
#define TK_VIRTUAL                         21
#define TK_RANGE                           22
#define TK_INTERVAL                        23
#define TK_PARTITION                       24
#define TK_BY                              25
#define TK_HASH                            26
#define TK_PARTITIONS                      27
#define TK_INTEGER                         28
#define TK_SUBPARTITION                    29
#define TK_SUBPARTITIONS                   30
#define TK_EVERY                           31
#define TK_STRING                          32
#define TK_USING                           33
#define TK_TIMESERIES                      34
#define TK_WITH                            35
#define TK_EQ                              36
#define TK_FLOAT                           37
#define TK_PLUS                            38
#define TK_MINUS                           39
#define TK_ID                              40
#define TK_ABORT                           41
#define TK_ACTION                          42
#define TK_AFTER                           43
#define TK_ALL                             44
#define TK_ASC                             45
#define TK_ATTACH                          46
#define TK_BEFORE                          47
#define TK_CASCADE                         48
#define TK_CAST                            49
#define TK_COLUMNKW                        50
#define TK_CONFLICT                        51
#define TK_DATABASE                        52
#define TK_DAY                             53
#define TK_DAY_OF_WEEK                     54
#define TK_DAY_OF_YEAR                     55
#define TK_DEFERRED                        56
#define TK_DEFINE                          57
#define TK_DESC                            58
#define TK_DETACH                          59
#define TK_EACH                            60
#define TK_EXCLUSIVE                       61
#define TK_EXTRACT                         62
#define TK_FAIL                            63
#define TK_FALSE                           64
#define TK_FILL                            65
#define TK_FOR                             66
#define TK_FORCE                           67
#define TK_GLOB                            68
#define TK_HOUR                            69
#define TK_IGNORE                          70
#define TK_IMMEDIATE                       71
#define TK_INITIALLY                       72
#define TK_INSTEAD                         73
#define TK_LAST                            74
#define TK_LIKE                            75
#define TK_LIKE_KW                         76
#define TK_LINEAR                          77
#define TK_MATCH                           78
#define TK_MATCH_RECOGNIZE                 79
#define TK_MEASURES                        80
#define TK_MICROSECOND                     81
#define TK_MILLISECOND                     82
#define TK_MINUTE                          83
#define TK_MONTH                           84
#define TK_NANOSECOND                      85
#define TK_NO                              86
#define TK_NONE                            87
#define TK_OF                              88
#define TK_OFFSET                          89
#define TK_ONE                             90
#define TK_PAST                            91
#define TK_PATTERN                         92
#define TK_PER                             93
#define TK_PLAN                            94
#define TK_PRAGMA                          95
#define TK_PREVIOUS                        96
#define TK_QUERY                           97
#define TK_RAISE                           98
#define TK_RECURSIVE                       99
#define TK_REGEXP                         100
#define TK_RELEASE                        101
#define TK_REPLACE                        102
#define TK_RESTRICT                       103
#define TK_ROW                            104
#define TK_ROWS                           105
#define TK_SAVEPOINT                      106
#define TK_SECOND                         107
#define TK_SKIP                           108
#define TK_TEMP                           109
#define TK_TIMESTAMP_TRUNC                110
#define TK_TIMESTAMPADD                   111
#define TK_TIMESTAMPDIFF                  112
#define TK_TO                             113
#define TK_TRIGGER                        114
#define TK_TRUE                           115
#define TK_UNBOUNDED                      116
#define TK_VACUUM                         117
#define TK_VIEW                           118
#define TK_WEEK                           119
#define TK_WITHIN                         120
#define TK_WITHOUT                        121
#define TK_YEAR                           122
#define TK_ANY                            123
#define TK_OR                             124
#define TK_XOR                            125
#define TK_AND                            126
#define TK_IS                             127
#define TK_BETWEEN                        128
#define TK_IN                             129
#define TK_ISNULL                         130
#define TK_NOTNULL                        131
#define TK_NE                             132
#define TK_GT                             133
#define TK_LE                             134
#define TK_LT                             135
#define TK_GE                             136
#define TK_ESCAPE                         137
#define TK_BITAND                         138
#define TK_BITOR                          139
#define TK_LSHIFT                         140
#define TK_RSHIFT                         141
#define TK_STAR                           142
#define TK_SLASH                          143
#define TK_REM                            144
#define TK_CONCAT                         145
#define TK_COLLATE                        146
#define TK_BITNOT                         147
#define TK_VARIABLE                       148
#define TK_LBRACE                         149
#define TK_CARET                          150
#define TK_DOLLAR                         151
#define TK_DROP                           152
#define TK_USER                           153
#define TK_IDENTIFIED                     154
#define TK_SET                            155
#define TK_PASSWORD                       156
#define TK_ROLE                           157
#define TK_GRANT                          158
#define TK_ON                             159
#define TK_SELECT                         160
#define TK_REVOKE                         161
#define TK_FROM                           162
#define TK_INDEX                          163
#define TK_DOT                            164
#define TK_ALTER                          165
#define TK_RENAME                         166
#define TK_ADD                            167
#define TK_UNION                          168
#define TK_EXCEPT                         169
#define TK_INTERSECT                      170
#define TK_VALUES                         171
#define TK_HINT_START                     172
#define TK_HINT_END                       173
#define TK_DISTINCT                       174
#define TK_RBRACE                         175
#define TK_JOIN                           176
#define TK_INNER                          177
#define TK_CROSS                          178
#define TK_LEFT                           179
#define TK_OUTER                          180
#define TK_RIGHT                          181
#define TK_FULL                           182
#define TK_NATURAL                        183
#define TK_ORDER                          184
#define TK_GROUP                          185
#define TK_HAVING                         186
#define TK_LIMIT                          187
#define TK_WHERE                          188
#define TK_DELETE                         189
#define TK_UPDATE                         190
#define TK_INTO                           191
#define TK_INSERT                         192
#define TK_BLOB                           193
#define TK_OVER                           194
#define TK_PRECEDING                      195
#define TK_FOLLOWING                      196
#define TK_CURRENT                        197
#define TK_CASE                           198
#define TK_WHEN                           199
#define TK_THEN                           200
#define TK_ELSE                           201
#define TK_TO_TEXT                        202
#define TK_TO_BLOB                        203
#define TK_TO_NUMERIC                     204
#define TK_TO_INT                         205
#define TK_TO_REAL                        206
#define TK_ISNOT                          207
#define TK_END_OF_FILE                    208
#define TK_ILLEGAL                        209
#define TK_SPACE                          210
#define TK_UNCLOSED_STRING                211
#define TK_FUNC                           212
#define TK_COLUMN                         213
#define TK_AGG_FUNCTION                   214
#define TK_AGG_COLUMN                     215
#define TK_CONST_FUNC                     216
#define TK_UMINUS                         217
#define TK_UPLUS                          218
#define TK_GISFUNC                        219
#endif
