/*
	Copyright (c) 2017 TOSHIBA Digital Solutions Corporation

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as
	published by the Free Software Foundation, either version 3 of the
	License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Affero General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef PARSERTOKEN_H
#define PARSERTOKEN_H
#define TK_SEMI                             1
#define TK_EXPLAIN                          2
#define TK_ANALYZE                          3
#define TK_BEGIN                            4
#define TK_TRANSACTION                      5
#define TK_COMMIT                           6
#define TK_END                              7
#define TK_ROLLBACK                         8
#define TK_TABLE                            9
#define TK_LP                              10
#define TK_RP                              11
#define TK_CREATE                          12
#define TK_IF                              13
#define TK_NOT                             14
#define TK_EXISTS                          15
#define TK_COMMA                           16
#define TK_PRIMARY                         17
#define TK_KEY                             18
#define TK_NULL                            19
#define TK_AS                              20
#define TK_VIRTUAL                         21
#define TK_RANGE                           22
#define TK_INTERVAL                        23
#define TK_PARTITION                       24
#define TK_BY                              25
#define TK_HASH                            26
#define TK_PARTITIONS                      27
#define TK_INTEGER                         28
#define TK_SUBPARTITION                    29
#define TK_SUBPARTITIONS                   30
#define TK_EVERY                           31
#define TK_STRING                          32
#define TK_USING                           33
#define TK_TIMESERIES                      34
#define TK_WITH                            35
#define TK_EQ                              36
#define TK_FLOAT                           37
#define TK_PLUS                            38
#define TK_MINUS                           39
#define TK_ID                              40
#define TK_ABORT                           41
#define TK_ACTION                          42
#define TK_AFTER                           43
#define TK_ASC                             44
#define TK_ATTACH                          45
#define TK_BEFORE                          46
#define TK_CASCADE                         47
#define TK_CAST                            48
#define TK_COLUMNKW                        49
#define TK_CONFLICT                        50
#define TK_DATABASE                        51
#define TK_DEFERRED                        52
#define TK_DESC                            53
#define TK_DETACH                          54
#define TK_EACH                            55
#define TK_EXCLUSIVE                       56
#define TK_FAIL                            57
#define TK_FOR                             58
#define TK_IGNORE                          59
#define TK_IMMEDIATE                       60
#define TK_INITIALLY                       61
#define TK_INSTEAD                         62
#define TK_LIKE_KW                         63
#define TK_MATCH                           64
#define TK_NO                              65
#define TK_PLAN                            66
#define TK_QUERY                           67
#define TK_OF                              68
#define TK_OFFSET                          69
#define TK_PRAGMA                          70
#define TK_RAISE                           71
#define TK_RECURSIVE                       72
#define TK_RELEASE                         73
#define TK_REPLACE                         74
#define TK_RESTRICT                        75
#define TK_ROW                             76
#define TK_SAVEPOINT                       77
#define TK_TEMP                            78
#define TK_TRIGGER                         79
#define TK_VACUUM                          80
#define TK_VIEW                            81
#define TK_WITHOUT                         82
#define TK_EXTRACT                         83
#define TK_TIMESTAMPADD                    84
#define TK_TIMESTAMPDIFF                   85
#define TK_YEAR                            86
#define TK_MONTH                           87
#define TK_DAY                             88
#define TK_WEEK                            89
#define TK_HOUR                            90
#define TK_MINUTE                          91
#define TK_SECOND                          92
#define TK_MILLISECOND                     93
#define TK_MICROSECOND                     94
#define TK_NANOSECOND                      95
#define TK_GLOB                            96
#define TK_LIKE                            97
#define TK_REGEXP                          98
#define TK_TRUE                            99
#define TK_FALSE                          100
#define TK_FORCE                          101
#define TK_TIMESTAMP_TRUNC                102
#define TK_DAY_OF_WEEK                    103
#define TK_DAY_OF_YEAR                    104
#define TK_WITHIN                         105
#define TK_FILL                           106
#define TK_NONE                           107
#define TK_PREVIOUS                       108
#define TK_LINEAR                         109
#define TK_ROWS                           110
#define TK_UNBOUNDED                      111
#define TK_ANY                            112
#define TK_OR                             113
#define TK_XOR                            114
#define TK_AND                            115
#define TK_IS                             116
#define TK_BETWEEN                        117
#define TK_IN                             118
#define TK_ISNULL                         119
#define TK_NOTNULL                        120
#define TK_NE                             121
#define TK_GT                             122
#define TK_LE                             123
#define TK_LT                             124
#define TK_GE                             125
#define TK_ESCAPE                         126
#define TK_BITAND                         127
#define TK_BITOR                          128
#define TK_LSHIFT                         129
#define TK_RSHIFT                         130
#define TK_STAR                           131
#define TK_SLASH                          132
#define TK_REM                            133
#define TK_CONCAT                         134
#define TK_COLLATE                        135
#define TK_BITNOT                         136
#define TK_DROP                           137
#define TK_USER                           138
#define TK_IDENTIFIED                     139
#define TK_SET                            140
#define TK_PASSWORD                       141
#define TK_ROLE                           142
#define TK_GRANT                          143
#define TK_ALL                            144
#define TK_ON                             145
#define TK_TO                             146
#define TK_SELECT                         147
#define TK_REVOKE                         148
#define TK_FROM                           149
#define TK_INDEX                          150
#define TK_DOT                            151
#define TK_ALTER                          152
#define TK_RENAME                         153
#define TK_ADD                            154
#define TK_UNION                          155
#define TK_EXCEPT                         156
#define TK_INTERSECT                      157
#define TK_VALUES                         158
#define TK_HINT_START                     159
#define TK_HINT_END                       160
#define TK_DISTINCT                       161
#define TK_JOIN                           162
#define TK_INNER                          163
#define TK_CROSS                          164
#define TK_LEFT                           165
#define TK_OUTER                          166
#define TK_RIGHT                          167
#define TK_FULL                           168
#define TK_NATURAL                        169
#define TK_ORDER                          170
#define TK_GROUP                          171
#define TK_HAVING                         172
#define TK_LIMIT                          173
#define TK_WHERE                          174
#define TK_DELETE                         175
#define TK_UPDATE                         176
#define TK_INTO                           177
#define TK_INSERT                         178
#define TK_BLOB                           179
#define TK_VARIABLE                       180
#define TK_OVER                           181
#define TK_PRECEDING                      182
#define TK_FOLLOWING                      183
#define TK_CURRENT                        184
#define TK_CASE                           185
#define TK_WHEN                           186
#define TK_THEN                           187
#define TK_ELSE                           188
#define TK_TO_TEXT                        189
#define TK_TO_BLOB                        190
#define TK_TO_NUMERIC                     191
#define TK_TO_INT                         192
#define TK_TO_REAL                        193
#define TK_ISNOT                          194
#define TK_END_OF_FILE                    195
#define TK_ILLEGAL                        196
#define TK_SPACE                          197
#define TK_UNCLOSED_STRING                198
#define TK_FUNC                           199
#define TK_COLUMN                         200
#define TK_AGG_FUNCTION                   201
#define TK_AGG_COLUMN                     202
#define TK_CONST_FUNC                     203
#define TK_UMINUS                         204
#define TK_UPLUS                          205
#define TK_GISFUNC                        206
#endif
